/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package api;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class helloConstants {

  public static final byte i = (byte)1;

  public static final Number myNumber = api.Number.ONE;

}
