/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package api;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.15.0)", date = "2022-01-04")
public enum Number implements org.apache.thrift.TEnum {
  ONE(0),
  TWO(2),
  THREE(10);

  private final int value;

  private Number(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static Number findByValue(int value) { 
    switch (value) {
      case 0:
        return ONE;
      case 2:
        return TWO;
      case 10:
        return THREE;
      default:
        return null;
    }
  }
}
